### ISSUE TITLE
断连重连

### ISSUE THREAD

**Issue by toxotguo** [patractlabs/substrate-archive#1]
这个分支 https://github.com/patractlabs/substrate-archive/tree/patractlabs-rebased-fmt
程序负载高或者db负载高的时候会出现报错
Disconnect
ERROR sqlx error: pool timed out while waiting for an open connection

之后程序就卡住

**Comment by liuchengxu** [comment]
有没有具体的重现方式？或者相关的日志？

**Comment by toxotguo** [comment]
搭建环境，跑/bin/polkadot-archive 从0开始执行polkadot主网数据，一定会出现，warn Disconnect

**Comment by toxotguo** [comment]
报错日志
[11:22] WARN Ending due to: Disconnected
